export const GAME_INFORMATIONS_REQUEST = 'GAME_INFORMATIONS_REQUEST';
export const GAME_INFORMATIONS_SUCCESS = 'GAME_INFORMATIONS_SUCCESS';
export const GAME_INFORMATIONS_FAIL = 'GAME_INFORMATIONS_FAIL';