export const INFORMATIONS_LIST_REQUEST = 'INFORMATIONS_LIST_REQUEST';
export const INFORMATIONS_LIST_SUCCESS = 'INFORMATIONS_LIST_SUCCESS';
export const INFORMATIONS_LIST_FAIL = 'INFORMATIONS_LIST_FAIL';