export const RANKS_ME_REQUEST = 'RANKS_ME_REQUEST';
export const RANKS_ME_SUCCESS = 'RANKS_ME_SUCCESS';
export const RANKS_ME_FAIL = 'RANKS_ME_FAIL';

export const RANKS_BEST_REQUEST = 'RANKS_BEST_REQUEST';
export const RANKS_BEST_SUCCESS = 'RANKS_BEST_SUCCESS';
export const RANKS_BEST_FAIL = 'RANKS_BEST_FAIL';